# Generated by Django 2.2.4 on 2019-08-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='courses',
            field=models.ManyToManyField(related_name='offering_colleges', to='College.Course'),
        ),
    ]
