# Generated by Django 2.2.4 on 2019-08-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0002_college_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='Engineering'),
            preserve_default=False,
        ),
    ]
