# Generated by Django 2.2.4 on 2019-08-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0003_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='entrance_exams',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='colleges', to='Exam.Exam'),
        ),
    ]
