# Generated by Django 2.2.4 on 2019-08-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0004_auto_20190820_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='entrance_exams',
            new_name='entrance_exam',
        ),
    ]
