# Generated by Django 2.2.6 on 2019-10-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0005_auto_20190820_0342'),
        ('College', '0005_auto_20190820_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('related_colleges', models.ManyToManyField(related_name='links', to='College.College')),
                ('related_exams', models.ManyToManyField(related_name='links', to='Exam.Exam')),
            ],
        ),
    ]
