# Generated by Django 2.2.6 on 2019-10-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0006_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.TextField(default=None),
        ),
    ]
