# Generated by Django 2.2.6 on 2019-10-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0005_auto_20190820_0342'),
        ('College', '0007_auto_20191015_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='entrance_exam',
        ),
        migrations.AddField(
            model_name='college',
            name='entrance_exam',
            field=models.ManyToManyField(related_name='colleges', to='Exam.Exam'),
        ),
    ]
