# Generated by Django 2.2.4 on 2019-08-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
