# Generated by Django 2.2.4 on 2019-08-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_auto_20190819_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='Date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='exam',
            name='coaching_centers',
            field=models.ManyToManyField(related_name='entrance_exams', to='Exam.Coaching'),
        ),
    ]
