# Generated by Django 2.2.4 on 2019-08-20 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_auto_20190820_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='coaching_centers',
        ),
        migrations.DeleteModel(
            name='Coaching',
        ),
    ]
