# Generated by Django 2.2.4 on 2019-08-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_auto_20190820_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='coaching_centers',
            field=models.ManyToManyField(related_name='entrance_exams', to='Exam.CoachingCenter'),
        ),
    ]
